version: '3.8'
services:
  php_fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Code source : :cached pour perf Windows
      - .:/var/www/html:cached
      # Cache et logs Symfony sur volumes Docker pour fluidité
      - ./docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
   
      - symfony_cache:/var/www/html/var/cache
      - symfony_logs:/var/www/html/var/log
    entrypoint: >
      sh -c "chown -R www-data:www-data /var/www/html/var/cache /var/www/html/var/log &&
             chmod -R 775 /var/www/html/var/cache /var/www/html/var/log &&
             php-fpm"
    expose:
      - "9000"
    environment:
      - APP_ENV=dev
      - APP_SECRET=!ChangeMe!
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8.0'     # utilise jusqu'à 8 cœurs
          memory: 12G     # jusqu'à 12 Go RAM

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changeme
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G

  webserver:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm
    restart: unless-stopped

volumes:
  db_data:
  symfony_cache:
  symfony_logs:
